#include <iostream>

int main() throw(std::logic_error) {
    try {
        
    }
    catch(...)
    {
        std::cout << "something error" << std::endl;
    }
    
}